calendarGames/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('games/', include('games.urls')),
    path('', RedirectView.as_view(url='/games/', permanent=True))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

games/urls.py
from . import views
from django.urls import path

app_name='games'
urlpatterns = [
    path('', views.GamesView.as_view(), name='index')
]

games/models.py
from django.db import models


class Game(models.Model):
    class Status(models.TextChoices):
        RESERVE = 'Резерв'
        PAID = 'Оплачено'
        CARRIED_OUT = 'Проведено'
        CANCELED = 'Отменено'
    datetime = models.DateTimeField()
    title = models.CharField(max_length=100)
    price = models.IntegerField()
    status = models.CharField(max_length=10, choices=Status.choices)

    def __str__(self):
        return self.title

games/views.py
import calendar
from datetime import datetime, timedelta
from .models import Game
from django.views import generic
from django.utils.safestring import mark_safe
from .utils import Calendar


class GamesView(generic.ListView):
    model = Game
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        date = get_date(self.request.GET.get('month', None), self.request.GET.get('day', None))
        cal = Calendar(date.year, date.month)
        html_calendar = cal.formatmonth(date.year, date.month)
        context['calendar'] = mark_safe(html_calendar)
        context['prev_month'] = prev_month(date)
        context['next_month'] = next_month(date)
        context['games'] = Game.objects.all().filter(datetime__year=date.year, datetime__month=date.month, datetime__day=date.day).order_by('datetime')
        return context


def get_date(month, day):
    if month:
        year, month = (int(x) for x in month.split('-'))
        if day:
            return datetime(year, month, day=int(day))
        return datetime(year, month, day=1)
    return datetime.today()


def prev_month(date):
    first = date.replace(day=1)
    previous_month = first - timedelta(days=1)
    month = 'month=' + str(previous_month.year) + '-' + str(previous_month.month)
    return month


def next_month(date):
    days_in_month = calendar.monthrange(date.year, date.month)[1]
    last = date.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

games/templates/index.html
<!doctype html>
<html lang="ru" class="h-100">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'games/css/styles.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <title>Document</title>
</head>
<body class="h-100">
    <div class="container bg-light h-100">
        <div class="row justify-content-md-center">
            <div class="calendar col-md-auto">
                {{ calendar }}
                <br>
                <div class="row justify-content-between">
                    <div class="col-5"><a class="btn btn-info left" href="{% url 'games:index' %}?{{ prev_month }}">Предедущий месяц</a></div>
                    <div class="col-5"><a class="btn btn-info right" href="{% url 'games:index' %}?{{ next_month }}">Следующий месяц</a></div>
                </div>
            </div>
        </div>
        <div style="height:50px"></div>
        <div class="row justify-content-center">
            <table class="table w-75">
                <thead>
                    <tr>
                        <th scope="col">Названия</th>
                        <th scope="col">Цена</th>
                        <th scope="col">Время</th>
                        <th scope="col">Статус</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in games %}
                        <tr>
                            <th scope="row">{{ item.title }}</th>
                            <td>{{ item.price }} руб</td>
                            <td>{{ item.datetime.day }}.{{ item.datetime.month }}.{{ item.datetime.year }}  {{ item.datetime.hour }}:{{ item.datetime.minute }}</td>
                            <td>{{ item.status }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>